name: Docker Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # ソースコードを取得
      - name: Checkout repository
        uses: actions/checkout@v4

      # Dockerビルド
      - name: Build Docker image
        run: |
          docker build -t monster-trainer .
          docker run --rm monster_game cargo test
